database:
  path: "src/main/resources/json/hotel.json"

apartment:
  allowApartmentStatusChange: true

saveOption:
  saveOnDisk: false

postgresDatabase:
  username: "postgres"
  password: "password"
  url: "jdbc:postgresql://localhost:5432/db_hotel_Andersen"
  pool: 30