database:
  path: "src/main/resources/json/hotel.json"

apartment:
  allowApartmentStatusChange: true

saveOption:
  saveOnDisk: true

postgresDatabase:
  POSTGRES_USER: "postgres"
  POSTGRES_PASS: "password"
  DB_URL: "jdbc:postgresql://localhost:5432/db_hotel_Andersen"
