create table Apartment (
                           apartment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           capacity int NOT NULL,
                           price double precision,
                           status varchar NOT NULL
);

create table Perk(
                     perk_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     name varchar NOT NULL,
                     price double precision
);

create table Client(
                       client_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar NOT NULL,
                       checkin timestamp,
                       checkout timestamp,
                       apartment_id bigint,
                       perk_id bigint,
                       staycost double precision,
                       quantityofpeople int
);

create table Client_Apartment (
                                  client_id bigint REFERENCES Client(client_id),
                                  apartment_id bigint REFERENCES Apartment(apartment_id),
                                  PRIMARY KEY(client_id, apartment_id)
);

create table Client_Perk (
                             client_id bigint REFERENCES Client(client_id),
                             perk_id bigint REFERENCES Perk(perk_id),
                             PRIMARY KEY(client_id, perk_id)
)